name: slimmy_card
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.3.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  flutter_phone_direct_caller: ^2.1.1
  flutter_dialpad: ^1.0.4
  call_log: ^4.0.0
  intl: ^0.18.0
  flutter_contacts: ^1.1.5+1
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true

  assets:
      - assets/image/
